In [1]:
'''Practical No.5: Write a NumPy program to implement following operation:

Name: Tank Yash
Eno: 216270307073
'''

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)



In [2]:
'''Practical No.5: Write a NumPy program to implement following operation:
• to find the maximum and minimum value of a given flattened array

Name: Tank Yash
Eno: 216270307073
'''

a = np.random.randint(1,20,(3,3))
print("Original Array:\n",a)

b = a.flatten()
print("\nFlatten a row-major order: \n", b)
print("Minimum element of array:\n",np.min(b))
print("Maximum element of array:\n",np.max(b))

Original Array:
 [[ 5 17 19]
 [14  7  2]
 [ 8 12 17]]

Flatten a row-major order: 
 [ 5 17 19 14  7  2  8 12 17]
Minimum element of array:
 2
Maximum element of array:
 19


In [3]:
'''Practical No.5: Write a NumPy program to implement following operation:
• to compute the mean, standard deviation, and variance of a given array 
along the second axis

Name: Tank Yash
Eno: 216270307073
'''

a = np.arange(1,10).reshape(3,3)
print("Original Array:\n",a)

print("Mean of a Second axis: ", np.mean(a, axis=1))
print("Standard Deviation Second axis: \n", np.std(a, axis=1))
print("Variance along Second axis: \n", np.var(a, axis=1))

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean of a Second axis:  [2. 5. 8.]
Standard Deviation Second axis: 
 [0.81649658 0.81649658 0.81649658]
Variance along Second axis: 
 [0.66666667 0.66666667 0.66666667]
