In [1]:
'''Practical No.2: Write a NumPy program to implement following operation

Name: Tank Yash
Eno: 216270307073
'''
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)



In [2]:
'''to convert a list of numeric values into a one-dimensional NumPy array

Name: Tank Yash
Eno: 216270307073
'''

l1 = [1,2,3,4]

print(np.array([l1]))

[[1 2 3 4]]


In [3]:
'''to create a 3x3 matrix with values ranging from 2 to 10

Name: Tank Yash
Eno: 216270307073
'''

a = [2,3,4]
b = [5,6,7]
c = [8,9,10]

array = np.array([a,b,c])
print("3*3 Matrix is: \n",array)

3*3 Matrix is: 
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [4]:
'''to append values at the end of an array

Name: Tank Yash
Eno: 216270307073
'''

l1 = [1,2,3,4]
print("The original array is: \n",np.array([l1]))

l1 = np.append(l1,[5])
print("After append value in the array: \n",l1)

The original array is: 
 [[1 2 3 4]]
After append value in the array: 
 [1 2 3 4 5]


In [5]:
'''to create another shape from an array without changing its data (3*2 to 2*3)

Name: Tank Yash
Eno: 216270307073
'''



'to create another shape from an array without changing its data (3*2 to 2*3)\n\nName: Tank Yash\nEno: 216270307073\n'