In [1]:
'''Practical No.3: Write a NumPy program to implement following operation

Name: Tank Yash
Eno: 216270307073
'''
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
'''
Write a NumPy program to implement following operation
• to split an array of 14 elements into 3 arrays, each with 2, 4, and 8 elements in the original order

Name: Tank Yash
Eno: 216270307073
'''
a = np.arange(14)
print("Oriinal array:\n",a)

print("\nAfter split array is:")
a1, a2, a3= np.split(a, [2,6])
print("First array:\n",a1,"\nSecond array:\n",a2,"\nThird array:\n",a3)

Oriinal array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]

After split array is:
First array:
 [0 1] 
Second array:
 [2 3 4 5] 
Third array:
 [ 6  7  8  9 10 11 12 13]


In [3]:
'''
Write a NumPy program to implement following operation:
• to stack arrays horizontally (column wise)

Name: Tank Yash
Eno: 216270307073
'''

a = np.array([[1, 2],[3,4]])
b = np.array([[6,7],[8,9]])
c = np.hstack((a, b))

print("Arrray 'a':\n",a)
print("Arrray 'b':\n",b)
print("Horizontally(column wise) array is:\n",c)

Arrray 'a':
 [[1 2]
 [3 4]]
Arrray 'b':
 [[6 7]
 [8 9]]
Horizontally(column wise) array is:
 [[1 2 6 7]
 [3 4 8 9]]
