In [1]:
'''Practical No.4: Write a NumPy program to implement following operation:

Name: Tank Yash
Eno: 216270307073
'''

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


In [2]:
'''Practical No.4: Write a NumPy program to implement following operation:
• to add, subtract, multiply, divide arguments element-wise

Name: Tank Yash
Eno: 216270307073
'''

x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]


In [3]:
'''Practical No.4: Write a NumPy program to implement following operation:
• to round elements of the array to the nearest integer

Name: Tank Yash
Eno: 216270307073
'''

a = np.random.randint(0,10,(3,3))
a = a/3

print("Array before Rounded:\n",a)
print("\nArray after Rounded:")
a = np.round(a)
print(a)

Array before Rounded:
 [[3.         1.         3.        ]
 [1.33333333 3.         0.66666667]
 [0.33333333 0.66666667 0.66666667]]

Array after Rounded:
[[3. 1. 3.]
 [1. 3. 1.]
 [0. 1. 1.]]


In [4]:
'''Practical No.4: Write a NumPy program to implement following operation:
• to calculate mean across dimension, in a 2D numpy array

Name: Tank Yash
Eno: 216270307073
'''

a = np.random.randint(1,50,(3,3))

print("Array:\n",a)

b = np.mean(a)
print("Mean of Array:\n",b)

Array:
 [[29  6  4]
 [39 45 40]
 [26 32  8]]
Mean of Array:
 25.444444444444443


In [5]:
'''Practical No.4: Write a NumPy program to implement following operation:
• to calculate the difference between neighboring elements, element-wise
of a given array

Name: Tank Yash
Eno: 216270307073
'''

a = np.random.randint(1,10,(3,3))
print("orijinal array:\n",a)

a = np.ediff1d(a)
a =np.reshape(a,(4,2))

print("\nArray after calculate difference:\n",a)

orijinal array:
 [[5 6 8]
 [8 2 1]
 [5 7 1]]

Array after calculate difference:
 [[ 1  2]
 [ 0 -6]
 [-1  4]
 [ 2 -6]]
