In [1]:
'''Practical No.5: Write a NumPy program to implement following operation:

Name: Tank Yash
Eno: 216270307073
'''

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)



In [2]:
'''Practical No.5: Write a NumPy program to implement following operation:
• to find the maximum and minimum value of a given flattened array

Name: Tank Yash
Eno: 216270307073
'''

a = np.random.randint(1,20,(3,3))
print("Original Array:\n",a)

b = a.flatten()
print("\nFlatten a row-major order: \n", b)
print("Minimum element of array:\n",np.min(b))
print("Maximum element of array:\n",np.max(b))

Original Array:
 [[17 12 17]
 [ 8 17 15]
 [18 14  2]]

Flatten a row-major order: 
 [17 12 17  8 17 15 18 14  2]
Minimum element of array:
 2
Maximum element of array:
 18


In [3]:
'''Practical No.5: Write a NumPy program to implement following operation:
• to compute the mean, standard deviation, and variance of a given array 
along the second axis

Name: Tank Yash
Eno: 216270307073
'''

a = np.arange(1,10).reshape(3,3)
print("Original Array:\n",a)

print("\nMean of a: ", np.mean(a))
print("Mean of a Second axis: ", np.mean(a, axis=0))
print("Mean of a Second axis: ", np.mean(a, axis=1))
print("\nStandard Deviation: \n", np.std(a))
print("Standard Deviation Second axis: \n", np.std(a, axis=0))
print("Standard Deviation Second axis: \n", np.std(a, axis=1))
print("\nVariance: \n", np.var(a))
print("Variance along Second axis: \n", np.var(a, axis=0))
print("Variance along Second axis: \n", np.var(a, axis=1))

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Mean of a:  5.0
Mean of a Second axis:  [4. 5. 6.]
Mean of a Second axis:  [2. 5. 8.]

Standard Deviation: 
 2.581988897471611
Standard Deviation Second axis: 
 [2.44948974 2.44948974 2.44948974]
Standard Deviation Second axis: 
 [0.81649658 0.81649658 0.81649658]

Variance: 
 6.666666666666667
Variance along Second axis: 
 [6. 6. 6.]
Variance along Second axis: 
 [0.66666667 0.66666667 0.66666667]
